# Generated by Django 4.2.1 on 2023-05-09 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=30)),
                ('endereco', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(max_length=5000)),
                ('valor_unitario', models.FloatField(max_length=10000000)),
                ('status', models.CharField(choices=[('FL', 'Finalizada'), ('EM', 'Em andamento'), ('CL', 'Cancelada')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cnpj', models.CharField(max_length=15, unique=True)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('quantidade', models.IntegerField(max_length=100000)),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.compra')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(max_length=5000)),
                ('valor_unitario', models.FloatField(max_length=10000000)),
                ('status', models.CharField(choices=[('FL', 'Finalizada'), ('EM', 'Em andamento'), ('CL', 'Cancelada')], max_length=2)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.cliente')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=30)),
                ('endereco', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='venda',
            name='id_vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.vendedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.fornecedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.produto'),
        ),
    ]
